version: '3.4'

services:
  blazorapp:
    image: ${DOCKER_REGISTRY-}blazorapp
    build:
      context: .
      dockerfile: BlazorApp/Dockerfile

  mvc:
    image: ${DOCKER_REGISTRY-}mvc
    build:
      context: .
      dockerfile: MVC/Dockerfile


  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile

